### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by tijeco** [tijeco/cinful#30]
This is a big one, but needs to be done. Right now, I really would like to configure the output location. Constantly overwriting `cinfulOut` is no bueno. Also, this will be how users can specify new input files (#2) but also input file extensions or list (#25). 

This needs to be done! Ideally it would be interfacable through the eventual wrapper as well as simply providing a config.json through snakemake,

**Comment by tijeco** [comment]
So this can be done in one of two ways:

Make a `config.yaml` file that looks like the following

```
outdir:
  "cinfulOut"
```

1. use `{outdir}` in an expand statement
2. use `{config[outdir]}`, with no expand statement

**Comment by AaronFeller** [comment]
Input and output locations have been updated and function correctly.
